language: c

compiler:
- gcc

script: make clean all

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "aRAWyfnQimtOyi1S5ClRYeGh4Jzjcgjto2fp6eNr54prFGkKqtPSJXpm/0pT6mTolqDNjEAAMcCTIJbunfsz+01SkrX5hBTkS/m8ub5ewckBON2DUwuA7A00eaRkgW6M+zHBewVAezGTOQd5qLVS2Wo9ADWYzbHsVN+SZJQ1dk0Td6jDORzpezr2iP+pNXSZPEaAPUq8i+LSsehKeE6GeV1OHoEeDmMMfpOF4DLG2XzJ69MZgMz6wdEuzb99tDwntEgcdSIVs5bLdthxvNuxTFDIwLctX2SbW8FNflCBG+Y/u8QTN9ivdzYozxXqw1ViP1n2HlmRZKZ/v9nbagzLrgXBZ8BDZL/AEQNMrPbHZXFF5aGdr9/5mnNB+2oFk6R17rSK4I9N6OcH24sr9byOI3PRey7j9+N6Mqto52G8tkXPWNvGB2y7yOKTIeNeJqcmUVJbwQmC/7x5jzTatfarwyK4/JqW2brYE5kJiRVGI2EfBkCG89h61c6wTdfpTdSNIuNVwDyKZwErVKnua91mieIFaatRgi1Jv7+bvObmtJS3TM2il8XuXe2Pn4nqZGRVVRwbSDFh26Uzv433cucWx5TZvI6uKP2Gzr62j2Fw6hQKHv/s8VYDisIoWcW0h3lxenQZr0B20FpASEuNAcKSm9pTMBoiUqFaINB1aJluCnc="

addons:
  coverity_scan:
    project:
      name: "amihub/ci-test"
      description: "<Your project description here>"
    notification_email: amihub7@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan
